// Catalog of every automated email the platform sends — the single reference for
// the admin "Automated emails" oversight page (Admin → Email → Automated).
//
// ┌─────────────────────────────────────────────────────────────────────────┐
// │ RULE: whenever you CREATE a new automated/transactional email anywhere    │
// │ (a Worker sendEmail() call, a confirmation/template fn, an automation or  │
// │ cron email), add an entry for it HERE in the SAME change — this catalog   │
// │ is maintained by hand and is the only source the oversight page reads.    │
// │ Add a new group to EMAIL_GROUPS below if the email doesn't fit an         │
// │ existing one, or it won't render. (This is a registry of email TYPES, not │
// │ a log of individual sends.)                                               │
// └─────────────────────────────────────────────────────────────────────────┘
//
// Phase 1 (now): read-only oversight — what each email is, what triggers it, who
// it goes to, the sender, subject, and what it contains.
// Phase 2 (next): each of these gets an `id`-keyed editable override stored in
// the DB; the Worker will render "the saved version if there is one, else the
// built-in default", and this catalog becomes the live source of truth.
//
// Sender key: unless noted, automated emails send from hello@tmke.co.uk
// (display name "TMKE") via Microsoft 365. Internal alerts go to the team.

export const EMAIL_CATALOG = [
  // ─────────────────────────── Social media ───────────────────────────
  {
    id: "smm_enquiry_ack",
    group: "Social media",
    name: "Enquiry — acknowledgement",
    audience: "client",
    trigger: "Someone submits the Social Media “Get in touch” form",
    fires: "POST /smm/enquiry",
    to: "The person enquiring",
    sender: "hello@tmke.co.uk",
    subject: "Thanks — we've got your message",
    summary: "Confirms we've received their enquiry and will reply within one working day, echoes their message back, and notes if a TMKE account was created for them.",
    fields: ["first_name", "message", "account_created"],
  },
  {
    id: "smm_enquiry_team",
    group: "Social media",
    name: "Enquiry — team alert",
    audience: "internal",
    trigger: "Someone submits the Social Media “Get in touch” form",
    fires: "POST /smm/enquiry",
    to: "SMM team (SMM_NOTIFY — Abby)",
    sender: "hello@tmke.co.uk",
    subject: "New enquiry — Social Media — {name}",
    summary: "Internal heads-up with the enquirer's name, business, email, phone, message, marketing opt-in and account status.",
    fields: ["full_name", "business", "email", "phone", "message", "marketing_opt_in"],
  },
  {
    id: "smm_brochure",
    group: "Social media",
    name: "Brochure delivery",
    audience: "client",
    trigger: "Someone requests the SMM brochure",
    fires: "POST /smm/brochure",
    to: "The requester",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE social media brochure",
    summary: "Delivers the social-media brochure with a download button, plus an account-created note when a login was set up.",
    fields: ["first_name", "brochure_url", "account_created"],
  },
  {
    id: "smm_discovery_client",
    group: "Social media",
    name: "Discovery call — confirmation",
    audience: "client",
    trigger: "Someone books a Social Media discovery call",
    fires: "POST /smm/discovery",
    to: "The client",
    sender: "hello@tmke.co.uk",
    subject: "Your call is booked — {date}",
    summary: "Confirms the call date and time, attaches a calendar invite (.ics), notes the new account, and explains how to rearrange.",
    attachments: "Calendar invite (.ics)",
    fields: ["first_name", "date", "time", "account_created"],
  },
  {
    id: "smm_discovery_team",
    group: "Social media",
    name: "Discovery call — team alert",
    audience: "internal",
    trigger: "Someone books a Social Media discovery call",
    fires: "POST /smm/discovery",
    to: "SMM team (SMM_NOTIFY — Abby)",
    sender: "hello@tmke.co.uk",
    subject: "New discovery call — Social Media — {name} — {date} {time}",
    summary: "Internal alert with the client's details and the booked slot.",
    fields: ["full_name", "business", "email", "phone", "date", "time"],
  },
  {
    id: "smm_meeting_invite",
    group: "Social media",
    name: "Meeting invite (from the CRM)",
    audience: "client",
    trigger: "Abby books a meeting on a lead's file with “send a diary invite” ticked",
    fires: "POST /smm/meeting",
    to: "The client",
    sender: "SMM mailbox (SMM_MAIL_SENDER) → hello@tmke.co.uk until set",
    subject: "Your meeting with TMKE — {date}",
    summary: "Confirms the booked meeting and attaches a calendar invite (.ics). Also creates the event on the SMM manager's diary.",
    attachments: "Calendar invite (.ics)",
    fields: ["first_name", "date", "time"],
  },
  {
    id: "smm_manual_message",
    group: "Social media",
    name: "Manual message from a customer file",
    audience: "client",
    trigger: "Abby writes a message on a lead's file and sends it (Emails tab / Send a message)",
    fires: "POST /booking/message (notify)",
    to: "The client",
    sender: "SMM mailbox (SMM_MAIL_SENDER) → hello@tmke.co.uk until set",
    subject: "Set by the sender",
    summary: "A free-text email written from the customer file, optionally with a document attached. Logged to the file's thread.",
    fields: ["name", "body", "subject", "attachment"],
  },

  // ─────────────────────────── Videography ───────────────────────────
  {
    id: "vid_booking_client",
    group: "Videography",
    name: "Booking — confirmation (branded)",
    audience: "client",
    trigger: "A videography booking is completed",
    fires: "POST /videography/book",
    to: "The client",
    sender: "hello@tmke.co.uk",
    subject: "Booking confirmed — {service}",
    summary: "Branded, per-service confirmation: a details table (service, package, add-ons, location, date, time, travel), the total inc. VAT, a “before your shoot/session/call” prep block, a manage-booking button, and a calendar invite.",
    attachments: "Calendar invite (.ics)",
    fields: ["name", "service", "package", "add_ons", "postcode", "date", "time", "travel", "total", "manage_url"],
  },
  {
    id: "vid_booking_team",
    group: "Videography",
    name: "Booking — team alert (Jack)",
    audience: "internal",
    trigger: "A videography booking is completed",
    fires: "POST /videography/book",
    to: "Jack (JACK_NOTIFY)",
    sender: "hello@tmke.co.uk",
    subject: "New booking — {service} — {name}",
    summary: "Internal booking summary: client, company, contact, package, add-ons, location, distance, travel surcharge, date/time, total and marketing opt-in.",
    fields: ["name", "company", "email", "phone", "package", "distance", "total"],
  },
  {
    id: "vid_enquiry_client",
    group: "Videography",
    name: "Enquiry — acknowledgement",
    audience: "client",
    trigger: "Someone submits a videography enquiry",
    fires: "POST /videography/enquiry",
    to: "The enquirer",
    sender: "hello@tmke.co.uk",
    subject: "Thanks for your enquiry — {service}",
    summary: "Confirms we've received the enquiry and will be in touch.",
    fields: ["name", "service"],
  },
  {
    id: "vid_enquiry_team",
    group: "Videography",
    name: "Enquiry — team alert",
    audience: "internal",
    trigger: "Someone submits a videography enquiry",
    fires: "POST /videography/enquiry",
    to: "Jack (JACK_NOTIFY)",
    sender: "hello@tmke.co.uk",
    subject: "New enquiry — {service} — {name}",
    summary: "Internal alert with the enquirer's details and message.",
    fields: ["name", "email", "phone", "service", "message"],
  },
  {
    id: "vid_brochure",
    group: "Videography",
    name: "Brochure delivery",
    audience: "client",
    trigger: "Someone requests the videography brochure",
    fires: "POST /videography/brochure",
    to: "The requester",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE videography brochure",
    summary: "Delivers the videography brochure with a download link, plus an account-created note where relevant.",
    fields: ["first_name", "brochure_url", "account_created"],
  },
  {
    id: "vid_discovery_client",
    group: "Videography",
    name: "Discovery call — confirmation",
    audience: "client",
    trigger: "Someone books a videography discovery call",
    fires: "POST /videography/discovery",
    to: "The client",
    sender: "hello@tmke.co.uk",
    subject: "Your discovery call is booked — {date}",
    summary: "Confirms the call date/time with Jack and attaches a calendar invite (.ics).",
    attachments: "Calendar invite (.ics)",
    fields: ["name", "date", "time"],
  },
  {
    id: "vid_discovery_team",
    group: "Videography",
    name: "Discovery call — team alert",
    audience: "internal",
    trigger: "Someone books a videography discovery call",
    fires: "POST /videography/discovery",
    to: "Jack (JACK_NOTIFY)",
    sender: "hello@tmke.co.uk",
    subject: "New discovery call — {name} — {date} {time}",
    summary: "Internal alert with the client's details and the booked slot.",
    fields: ["name", "email", "phone", "date", "time"],
  },
  {
    id: "vid_cancel",
    group: "Videography",
    name: "Booking cancelled",
    audience: "client",
    trigger: "A videography booking is cancelled",
    fires: "POST /videography/cancel",
    to: "The client (+ team alert to Jack)",
    sender: "hello@tmke.co.uk",
    subject: "Booking cancelled — {service}",
    summary: "Confirms the cancellation to the client; a matching internal alert goes to Jack.",
    fields: ["name", "service", "shoot_date"],
  },
  {
    id: "vid_reschedule",
    group: "Videography",
    name: "Booking rescheduled",
    audience: "client",
    trigger: "A videography booking is moved to a new time",
    fires: "POST /videography/reschedule",
    to: "The client (+ team alert to Jack)",
    sender: "hello@tmke.co.uk",
    subject: "Booking rescheduled — {date}",
    summary: "Confirms the new date/time to the client; a matching internal alert goes to Jack.",
    fields: ["name", "service", "date", "time"],
  },
  {
    id: "vid_gallery_ready_paid",
    group: "Videography",
    name: "Gallery ready — paid",
    audience: "client",
    trigger: "Jack sends the gallery from the client file, and the shoot is already paid for",
    fires: "POST /videography/gallery-email",
    to: "The gallery email (the address Pixieset gates downloads on)",
    sender: "hello@tmke.co.uk",
    subject: "Your gallery is ready",
    summary: "Gallery button, plus floor plan and any ad-hoc link. Carries the download PIN in a quote block, and tells them Pixieset will ask for that email address alongside it. Ends with the amendments clause from their agreement and a note that the gallery lasts about three months.",
    fields: ["name", "service", "gallery_url", "pin", "gallery_email", "floorplan_url", "extra_link"],
  },
  {
    id: "vid_gallery_ready_unpaid",
    group: "Videography",
    name: "Gallery ready — unpaid",
    audience: "client",
    trigger: "Jack sends the gallery and the shoot has not been paid for",
    fires: "POST /videography/gallery-email",
    to: "The gallery email",
    sender: "hello@tmke.co.uk",
    subject: "Your gallery is ready to view",
    summary: "Same links, but NO PIN. Explains the gallery is watermarked until payment clears and that the PIN follows automatically. Includes a Pay by card button when the invoice carries one, and attaches the outstanding invoice PDF.",
    fields: ["name", "service", "gallery_url", "invoice_number", "pay_url"],
  },
  {
    id: "vid_pin_released",
    group: "Videography",
    name: "PIN released after payment",
    audience: "client",
    trigger: "Payment lands on a shoot whose gallery has already been sent without the PIN",
    fires: "Stripe webhook (card) or POST /videography/release-pin (bank transfer)",
    to: "The gallery email",
    sender: "hello@tmke.co.uk",
    subject: "Your gallery is unlocked",
    summary: "The second email in the unpaid path. Thanks them for payment, gives the PIN and repeats which address to use with it, links to the gallery, says content stays available for three months and that we will remind them before it expires, and points them to Previous Bookings in TMKE Studio for anything else about the shoot. Sends once — pin_released_at guards it — and only when the gallery has already gone without the PIN.",
    fields: ["first_name", "pin", "gallery_email", "gallery_url"],
  },
  {
    id: "vid_payment_reminder",
    group: "Videography",
    name: "Payment reminder — day after the shoot",
    audience: "client",
    trigger: "Daily 08:00 cron: shot yesterday, invoice still outstanding, not already reminded",
    fires: "runVideographyChasers (cron 0 8 * * *)",
    to: "The client",
    sender: "hello@tmke.co.uk",
    subject: "Great to see you yesterday - here's what happens next",
    summary: "Thanks them for the session, explains Jack is editing and a gallery link will follow, then reminds them invoice {number} for {amount} is outstanding — attached, with a card link. Notes they will be able to view the gallery but downloads unlock on payment. A nudge rather than a chase: it lands on day three of a ten-day term.",
    fields: ["first_name", "invoice_number", "amount", "pay_url"],
  },
  {
    id: "vid_gallery_expiring",
    group: "Videography",
    name: "Gallery closing in a week",
    audience: "client",
    trigger: "Daily 08:00 cron: the gallery expiry date is seven days away",
    fires: "runVideographyChasers (cron 0 8 * * *)",
    to: "The gallery email",
    sender: "hello@tmke.co.uk",
    subject: "Your gallery expires in one week",
    summary: "Names the shoot, the date it was filmed and the date the gallery expires, links straight to it, and points out they can also reach it via Previous Bookings in TMKE Studio. Says plainly that content will not be viewable or downloadable afterwards. Sends once — expiry_warned_at guards it. Nothing hints that we keep an archive.",
    fields: ["first_name", "service", "shoot_date", "gallery_expires_on", "gallery_url"],
  },
  {
    id: "new_starter_booking_confirm",
    group: "Videography",
    name: "New-starter Studio Day — confirmation",
    audience: "client",
    trigger: "A TEG new starter books their free Studio Day",
    fires: "POST /new-starter/book",
    to: "The new starter (+ heads-up to Jack)",
    sender: "hello@tmke.co.uk",
    subject: "Your Studio Day is booked — TMKE",
    summary: "Confirms the booked date/time at the Content Studio, notes there's nothing to pay (part of their induction package), and that the address/prep will follow in a reminder. A matching internal booking alert goes to Jack (marked bill-to-TPE).",
    fields: ["name", "date", "time"],
  },

  // ─────────────────────────── Studio & packs ───────────────────────────
  {
    id: "waitlist_register",
    group: "Studio & packs",
    name: "Cancellation waitlist — confirmation",
    audience: "client",
    trigger: "Someone registers on the cancellation waitlist (a fully-booked service)",
    fires: "POST /waitlist/register",
    to: "The registrant",
    sender: "hello@tmke.co.uk",
    subject: "You're on the cancellation list — {service}",
    summary: "Confirms they're on the list with their preferred package/date/time, and that we'll message them when a slot opens.",
    fields: ["name", "service", "package", "date", "time"],
  },
  {
    id: "setup_reminder",
    group: "Studio & packs",
    name: "Set your password (unclaimed pack)",
    audience: "client",
    trigger: "A pack is paid for but no password is set after ~30 min (frequent cron)",
    fires: "Cron — every 5 min (runSetupReminders)",
    to: "The buyer",
    sender: "hello@tmke.co.uk",
    subject: "Set your password to unlock your TMKE pack",
    summary: "One-click link to set a password and unlock the purchased library. Sent once per unclaimed order.",
    fields: ["first_name", "pack", "link"],
  },
  {
    id: "post_reminder",
    group: "Studio & packs",
    name: "Scheduled post reminder",
    audience: "client",
    trigger: "A member has a post scheduled for today (daily 7am cron)",
    fires: "Cron — daily 07:00 (runReminders)",
    to: "The member",
    sender: "hello@tmke.co.uk",
    subject: "Your {platform} post is planned for today",
    summary: "Reminds the member their post is due today, includes the saved caption, and attaches the post image.",
    attachments: "Post image",
    fields: ["platform", "title", "caption"],
  },

  // ─────────────────────────── Automations engine ───────────────────────────
  {
    id: "automation_template",
    group: "Automations",
    name: "Automation-fired template",
    audience: "client",
    trigger: "An automation step fires (form submitted, account created, inbound email, etc.)",
    fires: "Automations engine (fireTrigger / /automations/tick)",
    to: "The contact",
    sender: "hello@tmke.co.uk",
    subject: "From the chosen email template",
    summary: "Sends a template built in the Email Studio, chosen by the automation. Content and subject are managed as an email template — this is the one type already editable today.",
    fields: ["contact fields", "template variables"],
    editableToday: true,
  },

  // ─────────────────────────── Account & auth ───────────────────────────
  {
    id: "auth_supabase",
    group: "Account & auth",
    name: "Sign-up & password-reset emails",
    audience: "client",
    trigger: "A member confirms sign-up or requests a password reset",
    fires: "Supabase Auth (not the Worker)",
    to: "The member",
    sender: "hello@tmke.co.uk (via Resend SMTP)",
    subject: "Supabase auth templates",
    summary: "Handled by Supabase, not the Worker — edited in the Supabase dashboard (Authentication → Email Templates). Listed here for completeness.",
    external: true,
    fields: ["confirmation_url", "reset_url"],
  },
  {
    id: "contact_account_invite",
    group: "Account & auth",
    name: "Contact — invite to create an account",
    audience: "client",
    trigger: "An admin clicks \"Invite them to create an account\" on a contact card that has no member hub account",
    fires: "POST /contacts/invite",
    to: "The contact",
    sender: "hello@tmke.co.uk",
    subject: "Create your TMKE account",
    summary: "Branded invite sent to a contact who doesn't yet have a member hub account, with a button that opens the join page (email pre-filled) so they can create one. The Worker double-checks no account exists before sending, and logs the invite as a note on the contact card.",
    fields: ["first_name", "join_url"],
    editableToday: false,
  },

  // ─────────────────────────── Admin & team ───────────────────────────
  {
    id: "admin_access_invite",
    group: "Admin & team",
    name: "Admin access — invitation",
    audience: "internal",
    trigger: "An admin grants someone admin-centre access (Settings → Admin access)",
    fires: "POST /admin/team",
    to: "The person being granted access",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE admin access",
    summary: "Tells a newly-granted admin how to sign in — with a temporary password if a login was just created for them, or a note to use their existing password if they already had an account.",
    fields: ["full_name", "temp_password", "login_url"],
  },
  {
    id: "admin_access_reset",
    group: "Admin & team",
    name: "Admin access — password reset",
    audience: "internal",
    trigger: "An admin resets someone's password (Settings → Admin access → Reset password)",
    fires: "POST /admin/team/reset",
    to: "The admin whose password was reset",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE admin password has been reset",
    summary: "Sends a fresh temporary password to an existing admin who needs one, with a prompt to change it after signing in.",
    fields: ["full_name", "temp_password", "login_url"],
  },

  // ─────────────────────────── Invoicing ───────────────────────────
  {
    id: "invoice_sent",
    group: "Invoicing",
    name: "Invoice — sent to recipient",
    audience: "client",
    trigger: "An admin clicks Send on an invoice (standalone builder or an SMM client's Invoicing tab)",
    fires: "POST /invoicing/invoices/send",
    to: "The invoice recipient (bill-to email); accounts dept CC'd (invoice_settings.accounts_cc_email — Paula & Danielle)",
    sender: "hello@tmke.co.uk",
    subject: "Invoice {number} from The Marketing Experts (Nationwide) Ltd (editable per send)",
    summary: "A covering email with the invoice number, total and due date, and the invoice attached as a PDF. The sender reviews it on a QuickBooks-style step and can edit the subject, body and CC before sending; a brand footer image (set in Invoicing Settings) is appended. Accounts is CC'd by default. Marks the invoice ‘sent’.",
    fields: ["number", "bill_to_name", "total", "due_date"],
  },
  {
    id: "invoice_dd_reminder",
    group: "Invoicing",
    name: "Direct Debit invoice — accounts reminder",
    audience: "internal",
    trigger: "A Direct Debit client's monthly ghost invoice is auto-raised (1st of the month, or when their Invoicing tab is opened)",
    fires: "cron runDdMonthly / POST /invoicing/dd/ensure → ensureDdInvoice",
    to: "The client's ghost-invoice recipient (smm_leads.dd_invoice_email; default danielle@tmke.co.uk). Never the customer.",
    sender: "hello@tmke.co.uk",
    subject: "Direct Debit invoice {number} — {client} ({month})",
    summary: "Internal reminder that a DD client's monthly invoice has been raised for the books (they pay by Direct Debit via QuickBooks, so the customer is never emailed). Shows client, period, amount, invoice number and DD collection date, with the full invoice PDF attached. Marked paid manually once the DD clears.",
    fields: ["number", "client", "month", "total", "due_date"],
  },
  {
    id: "invoice_voided",
    group: "Invoicing",
    name: "Invoice voided — accounts + admin",
    audience: "internal",
    trigger: "An admin voids an invoice (Void button on any invoice)",
    fires: "POST /invoicing/invoices/void",
    to: "Accounts (invoice_settings.accounts_cc_email) + CC the admin who voided it",
    sender: "hello@tmke.co.uk",
    subject: "Invoice {number} voided — {client}",
    summary: "Tells accounts (and the admin who did it) that an invoice has been voided and removed from the system, with the client, amount, who voided it and the reason given. The invoice itself is then deleted.",
    fields: ["number", "client", "total", "reason", "voided_by"],
  },
];

// Groups in display order.
export const EMAIL_GROUPS = ["Social media", "Videography", "Studio & packs", "Automations", "Account & auth", "Admin & team", "Invoicing"];
