// Catalog of every automated email the platform sends — the single reference for
// the admin "Automated emails" oversight page (Admin → Email → Automated).
//
// Phase 1 (now): read-only oversight — what each email is, what triggers it, who
// it goes to, the sender, subject, and what it contains.
// Phase 2 (next): each of these gets an `id`-keyed editable override stored in
// the DB; the Worker will render "the saved version if there is one, else the
// built-in default", and this catalog becomes the live source of truth.
//
// Sender key: unless noted, automated emails send from hello@tmke.co.uk
// (display name "TMKE") via Microsoft 365. Internal alerts go to the team.

export const EMAIL_CATALOG = [
  // ─────────────────────────── Social media ───────────────────────────
  {
    id: "smm_enquiry_ack",
    group: "Social media",
    name: "Enquiry — acknowledgement",
    audience: "client",
    trigger: "Someone submits the Social Media “Get in touch” form",
    fires: "POST /smm/enquiry",
    to: "The person enquiring",
    sender: "hello@tmke.co.uk",
    subject: "Thanks — we've got your message",
    summary: "Confirms we've received their enquiry and will reply within one working day, echoes their message back, and notes if a TMKE account was created for them.",
    fields: ["first_name", "message", "account_created"],
  },
  {
    id: "smm_enquiry_team",
    group: "Social media",
    name: "Enquiry — team alert",
    audience: "internal",
    trigger: "Someone submits the Social Media “Get in touch” form",
    fires: "POST /smm/enquiry",
    to: "SMM team (SMM_NOTIFY — Abby)",
    sender: "hello@tmke.co.uk",
    subject: "New enquiry — Social Media — {name}",
    summary: "Internal heads-up with the enquirer's name, business, email, phone, message, marketing opt-in and account status.",
    fields: ["full_name", "business", "email", "phone", "message", "marketing_opt_in"],
  },
  {
    id: "smm_brochure",
    group: "Social media",
    name: "Brochure delivery",
    audience: "client",
    trigger: "Someone requests the SMM brochure",
    fires: "POST /smm/brochure",
    to: "The requester",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE social media brochure",
    summary: "Delivers the social-media brochure with a download button, plus an account-created note when a login was set up.",
    fields: ["first_name", "brochure_url", "account_created"],
  },
  {
    id: "smm_discovery_client",
    group: "Social media",
    name: "Discovery call — confirmation",
    audience: "client",
    trigger: "Someone books a Social Media discovery call",
    fires: "POST /smm/discovery",
    to: "The client",
    sender: "hello@tmke.co.uk",
    subject: "Your call is booked — {date}",
    summary: "Confirms the call date and time, attaches a calendar invite (.ics), notes the new account, and explains how to rearrange.",
    attachments: "Calendar invite (.ics)",
    fields: ["first_name", "date", "time", "account_created"],
  },
  {
    id: "smm_discovery_team",
    group: "Social media",
    name: "Discovery call — team alert",
    audience: "internal",
    trigger: "Someone books a Social Media discovery call",
    fires: "POST /smm/discovery",
    to: "SMM team (SMM_NOTIFY — Abby)",
    sender: "hello@tmke.co.uk",
    subject: "New discovery call — Social Media — {name} — {date} {time}",
    summary: "Internal alert with the client's details and the booked slot.",
    fields: ["full_name", "business", "email", "phone", "date", "time"],
  },
  {
    id: "smm_meeting_invite",
    group: "Social media",
    name: "Meeting invite (from the CRM)",
    audience: "client",
    trigger: "Abby books a meeting on a lead's file with “send a diary invite” ticked",
    fires: "POST /smm/meeting",
    to: "The client",
    sender: "SMM mailbox (SMM_MAIL_SENDER) → hello@tmke.co.uk until set",
    subject: "Your meeting with TMKE — {date}",
    summary: "Confirms the booked meeting and attaches a calendar invite (.ics). Also creates the event on the SMM manager's diary.",
    attachments: "Calendar invite (.ics)",
    fields: ["first_name", "date", "time"],
  },
  {
    id: "smm_manual_message",
    group: "Social media",
    name: "Manual message from a customer file",
    audience: "client",
    trigger: "Abby writes a message on a lead's file and sends it (Emails tab / Send a message)",
    fires: "POST /booking/message (notify)",
    to: "The client",
    sender: "SMM mailbox (SMM_MAIL_SENDER) → hello@tmke.co.uk until set",
    subject: "Set by the sender",
    summary: "A free-text email written from the customer file, optionally with a document attached. Logged to the file's thread.",
    fields: ["name", "body", "subject", "attachment"],
  },

  // ─────────────────────────── Videography ───────────────────────────
  {
    id: "vid_booking_client",
    group: "Videography",
    name: "Booking — confirmation (branded)",
    audience: "client",
    trigger: "A videography booking is completed",
    fires: "POST /videography/book",
    to: "The client",
    sender: "hello@tmke.co.uk",
    subject: "Booking confirmed — {service}",
    summary: "Branded, per-service confirmation: a details table (service, package, add-ons, location, date, time, travel), the total inc. VAT, a “before your shoot/session/call” prep block, a manage-booking button, and a calendar invite.",
    attachments: "Calendar invite (.ics)",
    fields: ["name", "service", "package", "add_ons", "postcode", "date", "time", "travel", "total", "manage_url"],
  },
  {
    id: "vid_booking_team",
    group: "Videography",
    name: "Booking — team alert (Jack)",
    audience: "internal",
    trigger: "A videography booking is completed",
    fires: "POST /videography/book",
    to: "Jack (JACK_NOTIFY)",
    sender: "hello@tmke.co.uk",
    subject: "New booking — {service} — {name}",
    summary: "Internal booking summary: client, company, contact, package, add-ons, location, distance, travel surcharge, date/time, total and marketing opt-in.",
    fields: ["name", "company", "email", "phone", "package", "distance", "total"],
  },
  {
    id: "vid_enquiry_client",
    group: "Videography",
    name: "Enquiry — acknowledgement",
    audience: "client",
    trigger: "Someone submits a videography enquiry",
    fires: "POST /videography/enquiry",
    to: "The enquirer",
    sender: "hello@tmke.co.uk",
    subject: "Thanks for your enquiry — {service}",
    summary: "Confirms we've received the enquiry and will be in touch.",
    fields: ["name", "service"],
  },
  {
    id: "vid_enquiry_team",
    group: "Videography",
    name: "Enquiry — team alert",
    audience: "internal",
    trigger: "Someone submits a videography enquiry",
    fires: "POST /videography/enquiry",
    to: "Jack (JACK_NOTIFY)",
    sender: "hello@tmke.co.uk",
    subject: "New enquiry — {service} — {name}",
    summary: "Internal alert with the enquirer's details and message.",
    fields: ["name", "email", "phone", "service", "message"],
  },
  {
    id: "vid_brochure",
    group: "Videography",
    name: "Brochure delivery",
    audience: "client",
    trigger: "Someone requests the videography brochure",
    fires: "POST /videography/brochure",
    to: "The requester",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE videography brochure",
    summary: "Delivers the videography brochure with a download link, plus an account-created note where relevant.",
    fields: ["first_name", "brochure_url", "account_created"],
  },
  {
    id: "vid_discovery_client",
    group: "Videography",
    name: "Discovery call — confirmation",
    audience: "client",
    trigger: "Someone books a videography discovery call",
    fires: "POST /videography/discovery",
    to: "The client",
    sender: "hello@tmke.co.uk",
    subject: "Your discovery call is booked — {date}",
    summary: "Confirms the call date/time with Jack and attaches a calendar invite (.ics).",
    attachments: "Calendar invite (.ics)",
    fields: ["name", "date", "time"],
  },
  {
    id: "vid_discovery_team",
    group: "Videography",
    name: "Discovery call — team alert",
    audience: "internal",
    trigger: "Someone books a videography discovery call",
    fires: "POST /videography/discovery",
    to: "Jack (JACK_NOTIFY)",
    sender: "hello@tmke.co.uk",
    subject: "New discovery call — {name} — {date} {time}",
    summary: "Internal alert with the client's details and the booked slot.",
    fields: ["name", "email", "phone", "date", "time"],
  },
  {
    id: "vid_cancel",
    group: "Videography",
    name: "Booking cancelled",
    audience: "client",
    trigger: "A videography booking is cancelled",
    fires: "POST /videography/cancel",
    to: "The client (+ team alert to Jack)",
    sender: "hello@tmke.co.uk",
    subject: "Booking cancelled — {service}",
    summary: "Confirms the cancellation to the client; a matching internal alert goes to Jack.",
    fields: ["name", "service", "shoot_date"],
  },
  {
    id: "vid_reschedule",
    group: "Videography",
    name: "Booking rescheduled",
    audience: "client",
    trigger: "A videography booking is moved to a new time",
    fires: "POST /videography/reschedule",
    to: "The client (+ team alert to Jack)",
    sender: "hello@tmke.co.uk",
    subject: "Booking rescheduled — {date}",
    summary: "Confirms the new date/time to the client; a matching internal alert goes to Jack.",
    fields: ["name", "service", "date", "time"],
  },

  // ─────────────────────────── Studio & packs ───────────────────────────
  {
    id: "waitlist_register",
    group: "Studio & packs",
    name: "Cancellation waitlist — confirmation",
    audience: "client",
    trigger: "Someone registers on the cancellation waitlist (a fully-booked service)",
    fires: "POST /waitlist/register",
    to: "The registrant",
    sender: "hello@tmke.co.uk",
    subject: "You're on the cancellation list — {service}",
    summary: "Confirms they're on the list with their preferred package/date/time, and that we'll message them when a slot opens.",
    fields: ["name", "service", "package", "date", "time"],
  },
  {
    id: "setup_reminder",
    group: "Studio & packs",
    name: "Set your password (unclaimed pack)",
    audience: "client",
    trigger: "A pack is paid for but no password is set after ~30 min (frequent cron)",
    fires: "Cron — every 5 min (runSetupReminders)",
    to: "The buyer",
    sender: "hello@tmke.co.uk",
    subject: "Set your password to unlock your TMKE pack",
    summary: "One-click link to set a password and unlock the purchased library. Sent once per unclaimed order.",
    fields: ["first_name", "pack", "link"],
  },
  {
    id: "post_reminder",
    group: "Studio & packs",
    name: "Scheduled post reminder",
    audience: "client",
    trigger: "A member has a post scheduled for today (daily 7am cron)",
    fires: "Cron — daily 07:00 (runReminders)",
    to: "The member",
    sender: "hello@tmke.co.uk",
    subject: "Your {platform} post is planned for today",
    summary: "Reminds the member their post is due today, includes the saved caption, and attaches the post image.",
    attachments: "Post image",
    fields: ["platform", "title", "caption"],
  },

  // ─────────────────────────── Automations engine ───────────────────────────
  {
    id: "automation_template",
    group: "Automations",
    name: "Automation-fired template",
    audience: "client",
    trigger: "An automation step fires (form submitted, account created, inbound email, etc.)",
    fires: "Automations engine (fireTrigger / /automations/tick)",
    to: "The contact",
    sender: "hello@tmke.co.uk",
    subject: "From the chosen email template",
    summary: "Sends a template built in the Email Studio, chosen by the automation. Content and subject are managed as an email template — this is the one type already editable today.",
    fields: ["contact fields", "template variables"],
    editableToday: true,
  },

  // ─────────────────────────── Account & auth ───────────────────────────
  {
    id: "auth_supabase",
    group: "Account & auth",
    name: "Sign-up & password-reset emails",
    audience: "client",
    trigger: "A member confirms sign-up or requests a password reset",
    fires: "Supabase Auth (not the Worker)",
    to: "The member",
    sender: "hello@tmke.co.uk (via Resend SMTP)",
    subject: "Supabase auth templates",
    summary: "Handled by Supabase, not the Worker — edited in the Supabase dashboard (Authentication → Email Templates). Listed here for completeness.",
    external: true,
    fields: ["confirmation_url", "reset_url"],
  },

  // ─────────────────────────── Admin & team ───────────────────────────
  {
    id: "admin_access_invite",
    group: "Admin & team",
    name: "Admin access — invitation",
    audience: "internal",
    trigger: "An admin grants someone admin-centre access (Settings → Admin access)",
    fires: "POST /admin/team",
    to: "The person being granted access",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE admin access",
    summary: "Tells a newly-granted admin how to sign in — with a temporary password if a login was just created for them, or a note to use their existing password if they already had an account.",
    fields: ["full_name", "temp_password", "login_url"],
  },
  {
    id: "admin_access_reset",
    group: "Admin & team",
    name: "Admin access — password reset",
    audience: "internal",
    trigger: "An admin resets someone's password (Settings → Admin access → Reset password)",
    fires: "POST /admin/team/reset",
    to: "The admin whose password was reset",
    sender: "hello@tmke.co.uk",
    subject: "Your TMKE admin password has been reset",
    summary: "Sends a fresh temporary password to an existing admin who needs one, with a prompt to change it after signing in.",
    fields: ["full_name", "temp_password", "login_url"],
  },
];

// Groups in display order.
export const EMAIL_GROUPS = ["Social media", "Videography", "Studio & packs", "Automations", "Account & auth", "Admin & team"];
