-- Evergreen prompts, refined by Dani on 10 September 2026.
-- Updates the rows loaded from the shipped set (kind = 'evergreen', sort_order 0-15).
-- Safe to re-run. If the table has no evergreen rows, nothing changes and the hub
-- keeps using the same wording from the code.
begin;
update public.content_prompts set angle = 'Three questions buyers nearly always ask at a viewing', brief = 'Talk straight to camera. Put each question on screen as you answer it.', say = 'Start with the first question immediately. Answer all three in one or two sentences each, using what you hear from real buyers.', cover = 'The 3 questions buyers always ask. Use your face or a strong property shot behind the text.', is_video = true, updated_at = now() where kind = 'evergreen' and sort_order = 0;
update public.content_prompts set angle = 'The room buyers remember most, and why', brief = 'Use one strong room photo. In the caption, explain why this room stands out and what buyers tend to respond to.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 1;
update public.content_prompts set angle = '3 small changes that can make a home feel more viewing-ready', brief = 'Create a simple 4-slide carousel: hook, then one practical change per slide. Keep the advice realistic, low-cost and easy to action.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 2;
update public.content_prompts set angle = 'Come with me on a 60-second property tour', brief = 'Walk through one current listing. Start with the strongest feature rather than automatically starting at the front door.', say = 'Open with the reason someone should keep watching, then take viewers through 3 to 5 standout features. Finish with the area, price and CTA.', cover = 'Use the strongest property shot with “60-second tour” and the area or property type.', is_video = true, updated_at = now() where kind = 'evergreen' and sort_order = 3;
update public.content_prompts set angle = '5 things buyers notice before the viewing really starts', brief = 'Turn this into a 6-slide carousel: hook plus five details such as kerb appeal, entrance, light, smell and first impression. Add your own local experience.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 4;
update public.content_prompts set angle = 'What actually happens before your property goes live', brief = 'Film short behind-the-scenes clips while preparing a real listing: photos, measurements, floorplan, write-up, calls or final checks.', say = 'Use a simple voiceover or talk while you work. Explain what is happening and why each step matters to the launch.', cover = 'A candid behind-the-scenes frame with “Before your property goes live”.', is_video = true, updated_at = now() where kind = 'evergreen' and sort_order = 5;
update public.content_prompts set angle = 'Moving here? Save these 3 local spots', brief = 'Create a local carousel featuring three places people genuinely use: coffee, green space, schools, shops, walks or weekend spots. Make it specific to your patch.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 6;
update public.content_prompts set angle = 'Coming soon: give buyers one reason to watch this space', brief = 'Use one strong detail shot from an upcoming listing. Tease one feature, the property type or the area without revealing everything. End with a CTA to register interest.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 7;
update public.content_prompts set angle = 'What an estate agent actually does in a day', brief = 'Capture 4 to 6 honest moments across a normal working day. Include the less polished parts, not just viewings and keys.', say = 'Use timestamps or a short voiceover to explain each moment. Keep it natural and specific to your actual day.', cover = 'Use a candid frame from the day with “A day in estate agency”.', is_video = true, updated_at = now() where kind = 'evergreen' and sort_order = 8;
update public.content_prompts set angle = 'Why the highest valuation is not always the best valuation', brief = 'Create a 4-slide educational carousel: the tempting number, the risk of overpricing, what good pricing should consider, and your advice to sellers. Avoid attacking competitors.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 9;
update public.content_prompts set angle = 'Property myth or fact? Pick one sellers still believe', brief = 'Choose one common seller myth and build a simple 3-slide carousel: myth, reality, what the seller should do instead. Use a myth you genuinely hear in your area.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 10;
update public.content_prompts set angle = 'A result worth sharing, and what made the difference', brief = 'Share a genuine client result using a sold photo, testimonial or simple branded graphic. Add the useful context: the challenge, what you did and the outcome.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 11;
update public.content_prompts set angle = 'What is actually happening in your local property market?', brief = 'Give a short local market update using one or two useful data points. Explain what they mean rather than reading out a list of statistics.', say = 'Lead with the most useful takeaway for local sellers or buyers. Give the number, explain the context, then say what you would do with that information.', cover = 'Use the area name plus one headline figure or takeaway. Keep the cover simple.', is_video = true, updated_at = now() where kind = 'evergreen' and sort_order = 12;
update public.content_prompts set angle = 'First-time buyer? Sort this before you start offering', brief = 'Create a simple educational post around one practical first-time buyer step, such as agreement in principle, deposit position, solicitor or total buying costs. Keep it focused on one topic.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 13;
update public.content_prompts set angle = 'The story behind this sale', brief = 'Use a sold property as a mini case study. Structure the caption or carousel around the starting point, the challenge, what you did and the result. Use real figures only where you can substantiate them.', say = null, cover = null, is_video = false, updated_at = now() where kind = 'evergreen' and sort_order = 14;
update public.content_prompts set angle = '3 quick jobs to do before your next viewing', brief = 'Film three simple viewing-prep jobs being done. Choose practical actions a seller could complete quickly.', say = 'Name each job as you do it and explain in one sentence why it helps the viewing experience. Keep the pace quick.', cover = '“3 jobs before a viewing” over the strongest finished shot.', is_video = true, updated_at = now() where kind = 'evergreen' and sort_order = 15;
commit;
