-- TMKE — orders / purchases schema
-- Run AFTER schema.sql in the Supabase SQL editor.
--
-- Models a single-pack purchase. Each row is one paid pack for one buyer.
-- Buyers don't need an auth account at purchase time: contact details are
-- captured on the row. When they later complete the password setup,
-- user_id is filled in so they can sign in and load their library.
--
-- This is intentionally permissive for the stubbed checkout flow:
--   * anon can INSERT orders (no real payment provider yet)
--   * anyone with the order UUID can SELECT a single row (uuid is unguessable)
--   * authenticated (admin) users can do anything
-- When Stripe + webhooks land, tighten by moving inserts to a service-role
-- edge function and switching SELECT to user_id = auth.uid().

create extension if not exists "pgcrypto";

-- Sequence powering human-friendly invoice numbers like TMKE-2026-0001.
create sequence if not exists public.invoice_seq start 1001;

create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),

  -- Pack snapshot (keep title + price even if the pack is later edited).
  pack_id         uuid references public.packs(id) on delete set null,
  pack_slug       text not null,
  pack_title      text not null,
  amount_pence    integer not null check (amount_pence >= 0),

  -- Buyer details captured at checkout.
  buyer_name      text not null,
  buyer_email     text not null,
  buyer_phone     text,
  buyer_company   text,

  -- Payment metadata. payment_method tells us which UI tab was used;
  -- payment_ref is a stub id (Stripe PaymentIntent id once wired up).
  -- 'gift' is used by the admin "Gift a pack" tool (a £0 comp order).
  payment_method  text not null check (payment_method in ('apple_pay', 'google_pay', 'card', 'gift')),
  payment_ref     text,
  status          text not null default 'paid'
                  check (status in ('paid', 'refunded', 'failed', 'pending')),

  -- Invoice number, e.g. "TMKE-2026-0001". Generated by trigger below.
  invoice_number  text unique,

  -- Linked auth user once the buyer completes password setup.
  user_id         uuid references auth.users(id) on delete set null,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists orders_buyer_email_idx on public.orders (lower(buyer_email));
create index if not exists orders_user_id_idx     on public.orders (user_id);
create index if not exists orders_created_at_idx  on public.orders (created_at desc);

-- Bring existing databases in line with the constraint above (create table
-- if-not-exists won't alter an existing table). Safe to run repeatedly. This
-- is what fixes the admin "Gift a pack" tool failing with
-- "violates check constraint orders_payment_method_check".
alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders add constraint orders_payment_method_check
  check (payment_method in ('apple_pay', 'google_pay', 'card', 'gift'));

-- Touch updated_at
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- Auto-assign invoice_number on insert.
create or replace function public.assign_invoice_number()
returns trigger language plpgsql as $$
begin
  if new.invoice_number is null then
    new.invoice_number := 'TMKE-' ||
      to_char(coalesce(new.created_at, now()), 'YYYY') ||
      '-' || lpad(nextval('public.invoice_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists orders_assign_invoice on public.orders;
create trigger orders_assign_invoice
  before insert on public.orders
  for each row execute function public.assign_invoice_number();

-- ============================================================
-- RLS — see header comment for the policy rationale.
-- ============================================================
alter table public.orders enable row level security;

-- Anon checkout — anyone can insert a row.
drop policy if exists "orders insert anon" on public.orders;
create policy "orders insert anon"
  on public.orders for insert
  to anon, authenticated
  with check (true);

-- Anyone holding the uuid can read the row (uuids aren't guessable).
-- Lets the /edit/thanks page render the receipt without auth.
drop policy if exists "orders read by id" on public.orders;
create policy "orders read by id"
  on public.orders for select
  to anon, authenticated
  using (true);

-- Authenticated users may update orders (admin operations, claim flow).
drop policy if exists "orders update authed" on public.orders;
create policy "orders update authed"
  on public.orders for update
  to authenticated
  using (true)
  with check (true);

-- Delete is admin-only (no anon policy).
drop policy if exists "orders delete authed" on public.orders;
create policy "orders delete authed"
  on public.orders for delete
  to authenticated
  using (true);
