-- TMKE — add a full-resolution render per template design.
-- Each template already stores a lighter `thumb_url` (a 1080-wide JPEG, kept for
-- fast admin/studio list grids). `render_url` holds a LOSSLESS full-resolution
-- PNG of the same design (text and all), generated by the editor on save/publish
-- and refreshable in bulk via admin → "Regenerate previews". The pack catalogue
-- and pack detail pages prefer render_url so a design always shows crisp — no
-- JPEG artefacts on flat brand colours / text, and no hand-uploaded gallery
-- needed. Safe to re-run.

alter table public.templates
  add column if not exists render_url text;

-- Existing templates have no render yet — an admin should open the editor in
-- admin mode and click "Regenerate previews" once to backfill render_url (and
-- refresh thumb_url) across every design. Until then the catalogue transparently
-- falls back to thumb_url, so nothing breaks in the meantime.
