-- TMKE — extra awareness / "national day" dates for the content calendar.
-- Adds the fun, obscure observances on top of the bank holidays + key
-- marketing dates already seeded in calendar.sql. Great content prompts.
-- Run in the Supabase SQL editor. Safe to re-run (on conflict do nothing).
-- Mostly fixed-date observances (same day each year) + a couple of
-- variable ones (Pancake Day, UK World Book Day) computed per year.

insert into public.uk_holidays (date, name, kind, country) values
  -- ===== 2026 =====
  ('2026-01-04', 'World Braille Day',                 'awareness', 'uk'),
  ('2026-02-04', 'World Cancer Day',                  'awareness', 'uk'),
  ('2026-02-05', 'World Nutella Day',                 'awareness', 'uk'),
  ('2026-02-09', 'National Pizza Day',                'awareness', 'uk'),
  ('2026-02-17', 'Pancake Day (Shrove Tuesday)',      'awareness', 'uk'),
  ('2026-03-03', 'World Wildlife Day',                'awareness', 'uk'),
  ('2026-03-05', 'World Book Day (UK)',               'awareness', 'uk'),
  ('2026-03-14', 'Pi Day',                            'awareness', 'uk'),
  ('2026-03-20', 'International Day of Happiness',     'awareness', 'uk'),
  ('2026-03-21', 'World Poetry Day',                  'awareness', 'uk'),
  ('2026-03-22', 'World Water Day',                   'awareness', 'uk'),
  ('2026-04-07', 'World Health Day',                  'awareness', 'uk'),
  ('2026-04-21', 'National Tea Day',                  'awareness', 'uk'),
  ('2026-05-04', 'Star Wars Day',                     'awareness', 'uk'),
  ('2026-05-12', 'International Nurses Day',           'awareness', 'uk'),
  ('2026-06-05', 'World Environment Day',             'awareness', 'uk'),
  ('2026-06-08', 'World Oceans Day',                  'awareness', 'uk'),
  ('2026-07-17', 'World Emoji Day',                   'awareness', 'uk'),
  ('2026-08-01', 'Yorkshire Day',                     'awareness', 'uk'),
  ('2026-08-08', 'International Cat Day',              'awareness', 'uk'),
  ('2026-08-19', 'World Photography Day',             'awareness', 'uk'),
  ('2026-08-26', 'National Dog Day',                  'awareness', 'uk'),
  ('2026-09-19', 'Talk Like a Pirate Day',            'awareness', 'uk'),
  ('2026-09-21', 'International Day of Peace',         'awareness', 'uk'),
  ('2026-10-01', 'International Coffee Day',           'awareness', 'uk'),
  ('2026-10-04', 'World Animal Day',                  'awareness', 'uk'),
  ('2026-10-05', 'World Teachers'' Day',              'awareness', 'uk'),
  ('2026-10-10', 'World Mental Health Day',           'awareness', 'uk'),
  ('2026-10-16', 'World Food Day',                    'awareness', 'uk'),
  ('2026-11-13', 'World Kindness Day',                'awareness', 'uk'),
  ('2026-11-19', 'International Men''s Day',           'awareness', 'uk'),
  ('2026-12-10', 'Human Rights Day',                  'awareness', 'uk'),
  -- ===== 2027 (same fixed dates; variable ones recomputed) =====
  ('2027-01-04', 'World Braille Day',                 'awareness', 'uk'),
  ('2027-02-04', 'World Cancer Day',                  'awareness', 'uk'),
  ('2027-02-05', 'World Nutella Day',                 'awareness', 'uk'),
  ('2027-02-09', 'Pancake Day (Shrove Tuesday)',      'awareness', 'uk'),
  ('2027-02-09', 'National Pizza Day',                'awareness', 'uk'),
  ('2027-03-03', 'World Wildlife Day',                'awareness', 'uk'),
  ('2027-03-04', 'World Book Day (UK)',               'awareness', 'uk'),
  ('2027-03-14', 'Pi Day',                            'awareness', 'uk'),
  ('2027-03-20', 'International Day of Happiness',     'awareness', 'uk'),
  ('2027-03-21', 'World Poetry Day',                  'awareness', 'uk'),
  ('2027-03-22', 'World Water Day',                   'awareness', 'uk'),
  ('2027-04-07', 'World Health Day',                  'awareness', 'uk'),
  ('2027-04-21', 'National Tea Day',                  'awareness', 'uk'),
  ('2027-05-04', 'Star Wars Day',                     'awareness', 'uk'),
  ('2027-05-12', 'International Nurses Day',           'awareness', 'uk'),
  ('2027-06-05', 'World Environment Day',             'awareness', 'uk'),
  ('2027-06-08', 'World Oceans Day',                  'awareness', 'uk'),
  ('2027-07-17', 'World Emoji Day',                   'awareness', 'uk'),
  ('2027-08-01', 'Yorkshire Day',                     'awareness', 'uk'),
  ('2027-08-08', 'International Cat Day',              'awareness', 'uk'),
  ('2027-08-19', 'World Photography Day',             'awareness', 'uk'),
  ('2027-08-26', 'National Dog Day',                  'awareness', 'uk'),
  ('2027-09-19', 'Talk Like a Pirate Day',            'awareness', 'uk'),
  ('2027-09-21', 'International Day of Peace',         'awareness', 'uk'),
  ('2027-10-01', 'International Coffee Day',           'awareness', 'uk'),
  ('2027-10-04', 'World Animal Day',                  'awareness', 'uk'),
  ('2027-10-05', 'World Teachers'' Day',              'awareness', 'uk'),
  ('2027-10-10', 'World Mental Health Day',           'awareness', 'uk'),
  ('2027-10-16', 'World Food Day',                    'awareness', 'uk'),
  ('2027-11-13', 'World Kindness Day',                'awareness', 'uk'),
  ('2027-11-19', 'International Men''s Day',           'awareness', 'uk'),
  ('2027-12-10', 'Human Rights Day',                  'awareness', 'uk')
on conflict (date, name) do nothing;
